### ISSUE TITLE
Missing python scripts

### ISSUE THREAD

**Issue by hunglin59638** [wasade/exhaustive#1]
Dear the authors of exhaustive,

I noticed that the bash script `process.exhaustive.regions.sbatch` in your repository refers to two python scripts,
 `trim-to-max-length.py` and `deduplicate.py`, which are not included in the repository. 
Could you kindly provide guidance on how to obtain these missing scripts?

Thank you.

**Comment by wasade** [comment]
Hi @hunglin59638,

Good catch, thanks, I'll look at getting them uploaded today and will follow up on this issue

Best,
Daniel
